language: groovy

jdk:
- oraclejdk8

notifications:
  email: false

install:
- ./gradlew -version
- sudo add-apt-repository ppa:wpilib/toolchain -y
- sudo apt-get update -q
- sudo apt-get install frc-toolchain -y

script:
- ./gradlew build zipQuickstart --scan --stacktrace
- unzip Quickstart.zip -d quickstart_unzip
- cd quickstart_unzip/cpp
- ./gradlew clean build deploy -Pdeploy-dry --stacktrace
- cd ../java
- ./gradlew clean build deploy -Pdeploy-dry --stacktrace