version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: debian:stretch

    working_directory: ~/gradlerio

    environment:
      JVM_OPTS: -Xmx1500m
      TERM: dumb
    
    steps:
      - checkout
      - run: gradle dependencies wpi
      - run: gradle clean build deploy -Pdeploy-dry



