version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: debian:stretch

    working_directory: ~/gradlerio

    environment:
      JVM_OPTS: -Xmx1500m
      TERM: dumb
    
    steps:
      - checkout
      - run: ./gradlew dependencies
      - run: ./gradlew clean build
      - run: pushd quickstart/java
      - run: ./gradlew dependencies wpi clean build deploy -Pdeploy-dry --scan
      - run: popd; pushd quickstart/cpp
      - run: ./gradlew dependencies wpi clean build deploy -Pdeploy-dry --scan
      - run: popd