version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: debian:stretch

    working_directory: ~/gradlerio

    environment:
      JVM_OPTS: -Xmx1500m
      TERM: dumb
    
    steps:
      - checkout
      - run: ./gradlew dependencies
      - run: ./gradlew clean build
      - run: cd quickstart/java; ./gradlew dependencies wpi clean build deploy -Pdeploy-dry --scan
      - run: cd quickstart/cpp;  ./gradlew dependencies wpi installToolchain; chmod +x build/LINUX_TOOLCHAIN_INSTALL.sh; ./build/LINUX_TOOLCHAIN_INSTALL.sh; ./gradlew clean build deploy -Pdeploy-dry --scan